//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderMain()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long id { get; set; }
        public decimal totalAmount { get; set; }
        public decimal deliveryCharges { get; set; }
        public byte orderStatus { get; set; }
        public long customerInfoId { get; set; }
        public string trackingNumber { get; set; }
        public string comment { get; set; }
    
        public virtual CustomerInfo CustomerInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderMain OrderMain1 { get; set; }
        public virtual OrderMain OrderMain2 { get; set; }
    }
}
