//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_of_my_projectEntities1 : DbContext
    {
        public db_of_my_projectEntities1()
            : base("name=db_of_my_projectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catagory> Catagories { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderMain> OrderMains { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
    
        public virtual ObjectResult<Nullable<long>> SaveCustomerOrder(string name, string phone, string email, Nullable<decimal> totalAmount, string address, Nullable<byte> orderStatus, string trackingNumber, string products)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var totalAmountParameter = totalAmount.HasValue ?
                new ObjectParameter("TotalAmount", totalAmount) :
                new ObjectParameter("TotalAmount", typeof(decimal));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var orderStatusParameter = orderStatus.HasValue ?
                new ObjectParameter("OrderStatus", orderStatus) :
                new ObjectParameter("OrderStatus", typeof(byte));
    
            var trackingNumberParameter = trackingNumber != null ?
                new ObjectParameter("TrackingNumber", trackingNumber) :
                new ObjectParameter("TrackingNumber", typeof(string));
    
            var productsParameter = products != null ?
                new ObjectParameter("Products", products) :
                new ObjectParameter("Products", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("SaveCustomerOrder", nameParameter, phoneParameter, emailParameter, totalAmountParameter, addressParameter, orderStatusParameter, trackingNumberParameter, productsParameter);
        }
    
        public virtual ObjectResult<GetOrderDetailByCustomer_Result> GetOrderDetailByCustomer(Nullable<long> customerInfoId)
        {
            var customerInfoIdParameter = customerInfoId.HasValue ?
                new ObjectParameter("CustomerInfoId", customerInfoId) :
                new ObjectParameter("CustomerInfoId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderDetailByCustomer_Result>("GetOrderDetailByCustomer", customerInfoIdParameter);
        }
    }
}
