//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMain
    {
        public OrderMain()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long Id { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal DeliveryCharges { get; set; }
        public byte OrderStatus { get; set; }
        public long CustomerInfoId { get; set; }
        public string TrackingNumber { get; set; }
        public string Comments { get; set; }
    
        public virtual CustomerInfo CustomerInfo { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
