//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long id { get; set; }
        public long catagory_id { get; set; }
        public string name { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime create_date { get; set; }
        public decimal unit_price { get; set; }
        public string description { get; set; }
        public string image_path { get; set; }
        public bool is_active { get; set; }
        public string unit_text { get; set; }
        public decimal quantity { get; set; }
        public long unit_id { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
